### PR TITLE
Bump to V2.0.0

### PR DESCRIPTION
**Pull request by enver-haase**
According to
https://docs.google.com/document/d/1eVuAGAX4W2z3cq8KpayqaIhLFKAfUt5bJzsmcazSIDs/edit
this PR includes latest font files using the pom.xml that fetches from vaadin/vaadin-icons ('assets' directory). Please handle the PR there first (https://github.com/vaadin/vaadin-icons/pull/22).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons-addon/5)

### CODE REVIEW

**Comment by Artur-** [comment]
Reviewed 4 of 15 files at r3, 3 of 7 files at r4, 5 of 5 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[vaadin-icons/pom.xml, line 28 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXkDEWuvCIqOwuzssd:-KWXkDEWuvCIqOwuzsse:b-gzdaiw) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/pom.xml#L28)):_

> ``` XML
> 
>   <scm>
>       <url>scm:git:git@github.com/vaadin/vaadin-icons.git</url>
> ```

vaadin-icons-addon

---

_[vaadin-icons/pom.xml, line 29 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXkEit-UDs_WJVd61n:-KWXkEit-UDs_WJVd61o:b-gzdaiw) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/pom.xml#L29)):_

> ``` XML
>   <scm>
>       <url>scm:git:git@github.com/vaadin/vaadin-icons.git</url>
>       <connection>scm:git:git://github.com/vaadin/vaadin-icons.git</connection>
> ```

vaadin-icons-addon

---

_[vaadin-icons/pom.xml, line 30 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXkG-eCIypWi_MWmxB:-KWXkG-eCIypWi_MWmxC:bp3u1s9) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/pom.xml#L30)):_

> ``` XML
>       <url>scm:git:git@github.com/vaadin/vaadin-icons.git</url>
>       <connection>scm:git:git://github.com/vaadin/vaadin-icons.git</connection>
>

**Comment by enver-haase** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[vaadin-icons/pom.xml, line 28 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXkDEWuvCIqOwuzssd:-KWYKtRMkH6PxhQTVeU5:b-9qp1fp) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/pom.xml#L28)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> vaadin-icons-addon
> </details>
> No. We're in vaadin-icons-addon/vaadin-icons .  We are pulling the fonts from the Web Components repo "vaadin-icons" into the repo 'vaadin-icons-addon'. So my commit is correct.

---

_[vaadin-icons/pom.xml, line 29 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXkEit-UDs_WJVd61n:-KWYLB719TIC_62-DMZG:b-9qp1fp) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/pom.xml#L29)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> vaadin-icons-addon
> </details>
> No. We're in vaadin-icons-addon/vaadin-icons .  We are pulling the fonts from the Web Components repo "vaadin-icons" into the repo 'vaadin-icons-addon'. So my commit is correct.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Comment by enver-haase** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[vaadin-icons/pom.xml, line 30 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXkG-eCIypWi_MWmxB:-KWYLIuNYcWWGGZYrQSp:bgpbeno) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/pom.xml#L30)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Remove commented out stuff
> </details>
> No, please comment in the commented out stuff and leave my private repository 'enver-haase/vaadin-icons' alone. Of course, make sure that prior to doing so the correct tag (see below) exists.
>                     <scmVersion>v2.0.0</scmVersion>
>                     <scmVersionType>tag</scmVersionType>

Of course, comment out the unused issueManagement or point to the correct resource.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Comment by enver-haase** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[vaadin-icons-demo/src/main/webapp/VAADIN/themes/demo/demo.scss, line 33 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXkRjKWd5lLd1XMUmc:-KWYLzpzGyessV5cdOJ4:bql4no4) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons-demo/src/main/webapp/VAADIN/themes/demo/demo.scss#L33)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Why is this here? Shouldn't it come from the add-on, like the README describes
> </details>
> That's where the add-on places the font. I have no idea of how else we can reference it, i.e. I wouldn't know how to 'derive' from the AddOn fontface or such. Hand over to an SCSS guy, please. And teach me!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Comment by enver-haase** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[vaadin-icons/src/main/resources/VAADIN/addons/vaadin-icons/vaadin-icons.scss, line 3 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXkpYtdGceDFYSdKmz:-KWYMTeXq5WTnEtsDHbV:b-z4bh2v) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/src/main/resources/VAADIN/addons/vaadin-icons/vaadin-icons.scss#L3)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> > src: url('fonts/Vaadin-Icons.eot');
> > Shouldn't this be "../../addons/vaadin-icons/fonts/..." ? 
> > </details>
> > Possible - end of my knowledge, sorry!

---

_[vaadin-icons/src/main/resources/VAADIN/addons/vaadin-icons/vaadin-icons.scss, line 13 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXk_CFRMmrnkx_NMBG:-KWYMYb9iFggmIA5chXe:b-k7kr56) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/src/main/resources/VAADIN/addons/vaadin-icons/vaadin-icons.scss#L13)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> What's the point of an empty mixin? Needs a comment if this is needed because Vaadin automatically includes this based on the manifest attribute
> </details>
> No idea, what's a mixin...? I don't speak SCSS yet, happy to learn.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Comment by enver-haase** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[vaadin-icons/src/main/java/com/vaadin/VaadinIcons.java, line 1 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXo5iYHdB7cNASTZ8v:-KWYNAnJO0mDJ59egniT:b-pe1jqy) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/src/main/java/com/vaadin/VaadinIcons.java#L1)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> Should be com.vaadin.icons
> </details>
> Renaming in PR now. Please can you be clearer next time when you say <<Rename to "com.vaadin" "vaadin-icons">>.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Comment by enver-haase** [comment]
_[vaadin-icons/src/main/java/com/vaadin/icons/VaadinIcons.java, line 1 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWXo5iYHdB7cNASTZ8v:-KWYPVL6G9ZWJUaVTwSG:bjrtycp) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/d168e31407a397bfc3e1d40a5a99003dfed70916/vaadin-icons/src/main/java/com/vaadin/icons/VaadinIcons.java#L1)):_
Interesting how this swallows my sentences. You said 'rename to vaadin.com' but you meant Maven OrgId rather than package name. Would have helped to be clearer there. Updated PR.

> Renaming in PR now. Please can you be clearer next time when you say <>.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Comment by Legioth** [comment]
Reviewed 2 of 15 files at r3, 2 of 6 files at r5, 2 of 3 files at r6, 9 of 9 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[vaadin-icons/pom.xml, line 100 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWaw2wG11GWmWDWwQpJ:-KWaw2wG11GWmWDWwQpK:b-pntkyh) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/17b19a2d2e6b219828add8cf126cb7534ad62753/vaadin-icons/pom.xml#L100)):_

> ``` XML
>                       <configuration>
>                           <outputDirectory>${basedir}/src/main/resources/VAADIN/addons/vaadin-icons/fonts/</outputDirectory>
>                           <resources>          
> ```

nit: trailing whitespace

---

_[vaadin-icons-demo/src/main/webapp/VAADIN/themes/demo/demo.scss, line 33 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWazjPiASqYTBrsTb3E:-KWazjPjECt9OMxIKyBk:b-jog9oi) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/17b19a2d2e6b219828add8cf126cb7534ad62753/vaadin-icons-demo/src/main/webapp/VAADIN/themes/demo/demo.scss#L33)):_

> ``` SCSS
> 
> /* This font-face declaration must be outside your theme mixin. */
> @font-face {
> ```

Mention of this has been removed from the readme, but is still here. Is this part redundant or should the readme be updated?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Comment by Artur-** [comment]
Reviewed 1 of 6 files at r5, 2 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[vaadin-icons/pom.xml, line 100 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWaw2wG11GWmWDWwQpJ:-KWb0XgZ36ANorimZWJ8:b-hfpv0l) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/17b19a2d2e6b219828add8cf126cb7534ad62753/vaadin-icons/pom.xml#L100)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> nit: trailing whitespace
> </details>
> removed

---

_[vaadin-icons-demo/src/main/webapp/VAADIN/themes/demo/demo.scss, line 33 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5#-KWazjPiASqYTBrsTb3E:-KWb0gQKx7ap6Q76IpWh:ba3dfob) ([raw file](https://github.com/vaadin/vaadin-icons-addon/blob/17b19a2d2e6b219828add8cf126cb7534ad62753/vaadin-icons-demo/src/main/webapp/VAADIN/themes/demo/demo.scss#L33)):_
<details><summary>

<i>Previously, Legioth (Leif Åstrand) wrote…</i></summary>



> Mention of this has been removed from the readme, but is still here. Is this part redundant or should the readme be updated?
> </details>
> Removed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Comment by Legioth** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons-addon/5)_

**Pull request merged**
